---@diagnostic disable: undefined-field, unused-local
local cwd = vim.fn.getcwd()

describe("lib.numbers", function()
  local assert_eq = assert.is_equal
  local assert_true = assert.is_true
  local assert_false = assert.is_false

  before_each(function()
    vim.api.nvim_command("cd " .. cwd)
  end)

  local nums = require("fzfx.lib.numbers")

  describe("[test]", function()
    it("INT32_MIN/INT32_MAX", function()
      assert_eq(nums.INT32_MAX, 2 ^ 31 - 1)
      assert_eq(nums.INT32_MIN, -(2 ^ 31))
    end)
    it("bound", function()
      assert_eq(nums.bound(5, 1, 3), 3)
      assert_eq(nums.bound(2, 1, 13), 2)
      assert_eq(nums.bound(77), 77)
      assert_eq(nums.bound(77, nil, 29), 29)
    end)
    it("bound left", function()
      assert_eq(nums.bound(1, 1, 2), 1)
      assert_eq(nums.bound(1, 2, 3), 2)
      assert_eq(nums.bound(1, 3, 4), 3)
      assert_eq(nums.bound(2, 3, 4), 3)
      assert_eq(nums.bound(3, 3, 4), 3)
      assert_eq(nums.bound(4, 3, 4), 4)
      assert_eq(nums.bound(-10, nil), -10)
    end)
    it("bound right", function()
      assert_eq(nums.bound(1, 1, 5), 1)
      assert_eq(nums.bound(3, 2, 6), 3)
      assert_eq(nums.bound(5, 3, 7), 5)
      assert_eq(nums.bound(9, 3, 8), 8)
      assert_eq(nums.bound(10, 3, 9), 9)
      assert_eq(nums.bound(15, 3, 10), 10)
      assert_eq(nums.bound(15, 3), 15)
    end)
    it("inc_id", function()
      local id1 = nums.inc_id()
      assert_true(id1 >= 1)
      local id2 = nums.inc_id()
      assert_eq(id2, id1 + 1)
      local id3 = nums.inc_id()
      assert_eq(id3, id2 + 1)
      assert_true(nums.inc_id() == nums.inc_id() - 1)
    end)
    it("positive/negative", function()
      assert_true(nums.positive(1))
      assert_true(nums.negative(-1))
      assert_true(nums.non_positive(0))
      assert_true(nums.non_positive(-1))
      assert_true(nums.non_negative(0))
      assert_true(nums.non_negative(1))
    end)
  end)
end)
